version: "3.9"
services:
  postgres-1:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "KULIKOVA_206"
      POSTGRES_USER: "KULIKOVA_206"
      POSTGRES_PASSWORD: "KULIKOVA_206"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/Hospital.sql:/docker-entrypoint-initdb.d/Hospital.sql
      - ./dz/postgres-1:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  postgres-2:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "KULIKOVA_206"
      POSTGRES_USER: "KULIKOVA_206"
      POSTGRES_PASSWORD: "KULIKOVA_206"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/Library.sql:/docker-entrypoint-initdb.d/Library.sql
      - ./dz/postgres-2:/var/lib/postgresql/data
    ports:
      - "5444:5432"
  postgres-3:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "KULIKOVA_206"
      POSTGRES_USER: "KULIKOVA_206"
      POSTGRES_PASSWORD: "KULIKOVA_206"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/Station.sql:/docker-entrypoint-initdb.d/Station.sql
      - ./dz/postgres-3:/var/lib/postgresql/data
    ports:
      - "5455:5432"
